### ISSUE TITLE
Remove .git folder from npm registry

### ISSUE THREAD

**Issue by zm1994** [rosette-api/nodejs#66]
Please remove .git folder from the npm registry. When I try install another package after installed 'rosette-api', I will get the npm error 
'npm ERR! code EISGIT
npm ERR! git /home/user/projects/project/node_modules/rosette-api: Appears to be a git repo or submodule.
npm ERR! git     /home/user/projects/project/node_modules/rosette-api
npm ERR! git Refusing to remove it. Update manually,
npm ERR! git or move it out of the way first.
'

**Comment by cp2boston** [comment]
Hi zm1994!  I apologize for including the .git folder.  According to the npmignore documentation, the .git folder is supposed to be ignored by default, so I never bothered to check.  I appreciate your bringing it to our attention.  I have updated the package so that it no longer includes the .git folder as well as .grunt, .travis.yml and the two Jenkinsfiles.

Version 1.8.1 should be on npm.  Please let me know if it resolves your error.

**Comment by zm1994** [comment]
Thank you. All works fine
